// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibeaxiumxuzokodtyuvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliZWF4aXVteHV6b2tvZHR5dXZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0NDEwNjIsImV4cCI6MjA1NjAxNzA2Mn0._F48j43aHNOBphHc1A-Gt0Ef9ZGYWFMDjNmFZtKCJAg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);